const graffitiImages = [
  {
    id: "0",
    location: "Bashtola, Nurerchala Rd, Dhaka 1212",
    district: "Dhaka",
    photoCredit: "Asef Hossain Khan",
    artists: "Unknown",
    description: "Foolish acts done by the then government",
    url: "/graffiti_images/binodon_bhandar.JPEG",
  },
  {
    id: "1",
    location: "Bashtola, Nurerchala Rd, Dhaka 1212",
    district: "Dhaka",
    photoCredit: "Asef Hossain Khan",
    artists: "Unknown",
    description:
      "Encouraging political discussion in tongs, which would otherwise be avoided by the young generation",
    url: "/graffiti_images/tong.JPEG",
  },
  {
    id: "2",
    location: "Tejgaon, Dhaka",
    district: "Dhaka",
    photoCredit: "Ashfaq Hossain Khan",
    artists: "Unknown",
    description: "Different significant events of the revolution",
    url: "/graffiti_images/different_events.jpeg",
  },
  {
    id: "3",
    location: "Tejgaon, Dhaka",
    district: "Dhaka",
    photoCredit: "Ashfaq Hossain Khan",
    artists: "Unknown",
    description: "Beautiful portrayal of unity ",
    url: "/graffiti_images/pata_chera_nished.jpeg",
  },
  {
    id: "4",
    location: "Purana Paltan Line, Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Expression of remonstrance through lyrics ",
    url: "/graffiti_images/amar_bhoy_nai.jpg",
  },
  {
    id: "5",
    location: "Central Shahid Minar Road , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/bichar_korbe_k.jpg",
  },
  {
    id: "6",
    location: "Central Shahid Minar Road , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/khola_janala.jpg",
  },
  {
    id: "7",
    location: "Central Shahid Minar Road , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Rahat, Simi, Hayat, Sifat",
    description: "Graffiti",
    url: "/graffiti_images/starry_night.jpg",
  },
  {
    id: "8",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Kabya, Nowshin, Laisa, Mahir, Oibya",
    description: "Graffiti",
    url: "/graffiti_images/gono_manush.jpg",
  },
  {
    id: "9",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/bikkhob.jpg",
  },
  {
    id: "10",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/gujob_raw.jpg",
  },
  {
    id: "11",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Efti, Shela, Tasmia",
    description: "Graffiti",
    url: "/graffiti_images/injured.jpg",
  },
  {
    id: "12",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/nari.jpg",
  },
  {
    id: "13",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/natok_kom_koro_pio.jpg",
  },
  {
    id: "14",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/hungkar.jpg",
  },
  {
    id: "15",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/satellite.jpg",
  },
  {
    id: "16",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/36July.jpg",
  },
  {
    id: "17",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/hat_baksho.jpg",
  },
  {
    id: "18",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/bolidan.jpg",
  },
  {
    id: "19",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/tatakae.jpg",
  },
  {
    id: "20",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/rebirth.jpg",
  },
  {
    id: "21",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/jatrira_hushiar.jpg",
  },
  {
    id: "22",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/onek_manush.jpg",
  },
  {
    id: "23",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/vengeance.jpg",
  },
  {
    id: "24",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/arise.jpg",
  },
  {
    id: "25",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/agun_agun.jpg",
  },
  {
    id: "26",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/abar_nari.jpg",
  },
  {
    id: "27",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/freedom.jpg",
  },
  {
    id: "28",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/jamuna_tv.jpg",
  },
  {
    id: "29",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/rokto_lal.jpg",
  },
  {
    id: "30",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/gahilam.jpg",
  },
  {
    id: "31",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/shob_dekhe_felsi.jpg",
  },
  {
    id: "32",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/shobbho_ho.jpg",
  },
  {
    id: "33",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/jani_na.jpg",
  },
  {
    id: "34",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/karar_oi_louho.jpg",
  },
  {
    id: "35",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/desh_shonkskar.jpg",
  },
  {
    id: "36",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/ek_dofa.jpg",
  },
  {
    id: "37",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Sirajum",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/chokh.jpg",
  },
  {
    id: "38",
    location: "Mymensingh",
    district: "Mymensingh",
    photoCredit: "Unknown",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/graffiti_street.jpg",
  },
  {
    id: "39",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/fire.jpg",
  },
  {
    id: "40",
    location: "Central Shahid Minar Road , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/child_copter.jpg",
  },
];

export default graffitiImages;
