const graffitiImages = [
  {
    id: "49",
    location: "Banani 11 bridge, Dhaka",
    district: "Dhaka",
    photoCredit: "Tanzil Islam Fahad",
    artists: "Sake",
    description:
      "Inspired from the recent times - jago - a message for the mass.",
    url: "/graffiti_images/sake.jpg",
    thumbnail_url: "/graffiti_thumbnails/sake.jpg",
  },
  {
    id: "6",
    location: "Central Shahid Minar Road , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/khola_janala.jpg",
    thumbnail_url: "/graffiti_thumbnails/khola_janala.jpg",
  },
  {
    id: "29",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/rokto_lal.jpg",
    thumbnail_url: "/graffiti_thumbnails/rokto_lal.jpg",
  },
  {
    id: "45",
    location: "Malibagh, Dhaka",
    district: "Dhaka",
    photoCredit: "Sadia Akter",
    artists: "Maria, Alo, Samia",
    description: "Referring to the Shubodh Character",
    url: "/graffiti_images/shubodh_ghure_dara.jpg",
    thumbnail_url: "/graffiti_thumbnails/shubodh_ghure_dara.jpg",
  },
  {
    id: "14",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/hungkar.jpg",
    thumbnail_url: "/graffiti_thumbnails/hungkar.jpg",
  },
  {
    id: "33",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/jani_na.jpg",
    thumbnail_url: "/graffiti_thumbnails/jani_na.jpg",
  },
  {
    id: "42",
    location: "Bhuigor bus stand, Underpass, Naraynganj",
    district: "Naraynganj",
    photoCredit: "Maya",
    artists: "Maya, Mithila ",
    description: "",
    url: "/graffiti_images/maya_second.jpg",
    thumbnail_url: "/graffiti_thumbnails/maya_second.jpg",
  },
  {
    id: "31",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/shob_dekhe_felsi.jpg",
    thumbnail_url: "/graffiti_thumbnails/shob_dekhe_felsi.jpg",
  },
  {
    id: "23",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/vengeance.jpg",
    thumbnail_url: "/graffiti_thumbnails/vengeance.jpg",
  },
  {
    id: "5",
    location: "Central Shahid Minar Road , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/bichar_korbe_k.jpg",
    thumbnail_url: "/graffiti_thumbnails/bichar_korbe_k.jpg",
  },
  {
    id: "36",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/ek_dofa.jpg",
    thumbnail_url: "/graffiti_thumbnails/ek_dofa.jpg",
  },
  {
    id: "2",
    location: "Tejgaon, Dhaka",
    district: "Dhaka",
    photoCredit: "Ashfaq Hossain Khan",
    artists: "Unknown",
    description: "Different significant events of the revolution",
    url: "/graffiti_images/different_events.jpg",
    thumbnail_url: "/graffiti_thumbnails/different_events.jpg",
  },
  {
    id: "18",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/bolidan.jpg",
    thumbnail_url: "/graffiti_thumbnails/bolidan.jpg",
  },
  {
    id: "12",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/nari.jpg",
    thumbnail_url: "/graffiti_thumbnails/nari.jpg",
  },
  {
    id: "41",
    location: "Dhanmondi 11/A, Girls' School Road, Dhaka",
    district: "Dhaka",
    photoCredit: "Ajwad Al Muyeed",
    artists:
      "Nafis Kabir, Mahdia Ahseen, Rafiun Nabi Nahin, Nafisa Ambrin, Shaifta Morshed, Safwan Bin Zaman, Rehnuma Abanty, Ajwad Sadman, Dhian Giri, Nirvana Haque Arpita, Sadman Sion, Carin Nathan, Reedwan Reshad, Procheta Khan, Nishat Jahan Toa, Lamisa Tasneem Arnee, Syeda Adreena Aysha, Ribhu Roddur.",
    description:
      "A timeline of events rolling throughout the Quota Movement upto the emancipation from the autocratic regime.",
    url: "/graffiti_images/rafi_nahin.jpg",
    thumbnail_url: "/graffiti_thumbnails/rafi_nahin.jpg",
  },
  {
    id: "34",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/karar_oi_louho.jpg",
    thumbnail_url: "/graffiti_thumbnails/karar_oi_louho.jpg",
  },
  {
    id: "17",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/hat_baksho.jpg",
    thumbnail_url: "/graffiti_thumbnails/hat_baksho.jpg",
  },
  {
    id: "26",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/abar_nari.jpg",
    thumbnail_url: "/graffiti_thumbnails/abar_nari.jpg",
  },
  {
    id: "4",
    location: "Purana Paltan Line, Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Expression of remonstrance through lyrics ",
    url: "/graffiti_images/amar_bhoy_nai.jpg",
    thumbnail_url: "/graffiti_thumbnails/amar_bhoy_nai.jpg",
  },
  {
    id: "1",
    location: "Bashtola, Nurerchala Rd, Dhaka 1212",
    district: "Dhaka",
    photoCredit: "Asef Hossain Khan",
    artists: "Unknown",
    description:
      "Encouraging political discussion in tongs, which would otherwise be avoided by the young generation",
    url: "/graffiti_images/tong.jpg",
    thumbnail_url: "/graffiti_thumbnails/tong.jpg",
  },
  {
    id: "27",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/freedom.jpg",
    thumbnail_url: "/graffiti_thumbnails/freedom.jpg",
  },
  {
    id: "0",
    location: "Bashtola, Nurerchala Rd, Dhaka 1212",
    district: "Dhaka",
    photoCredit: "Asef Hossain Khan",
    artists: "Unknown",
    description: "Foolish acts done by the then government",
    url: "/graffiti_images/binodon_bhandar.jpg",
    thumbnail_url: "/graffiti_thumbnails/binodon_bhandar.jpg",
  },
  {
    id: "20",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/rebirth.jpg",
    thumbnail_url: "/graffiti_thumbnails/rebirth.jpg",
  },
  {
    id: "37",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Sirajum",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/chokh.jpg",
    thumbnail_url: "/graffiti_thumbnails/chokh.jpg",
  },
  {
    id: "48",
    location: "Varendra Museum Area, Rajshahi ",
    district: "Rajshahi",
    photoCredit: "Salma Akter Any ",
    artists: "Any, Maisoon, Labib, Mehedi, Sakib, Azmira, Nusrat, Jubayer",
    description:
      "Purpose of this mural was to showcase a continuous flow of movement that started with quota and ended up achieving a new Bangladesh",
    url: "/graffiti_images/any.jpg",
    thumbnail_url: "/graffiti_thumbnails/any.jpg",
  },
  {
    id: "39",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/fire.jpg",
    thumbnail_url: "/graffiti_thumbnails/fire.jpg",
  },
  {
    id: "44",
    location: "Rajarbagh, Dhaka",
    district: "Dhaka",
    photoCredit: "Sadia Akter",
    artists: "Hasibul Hassan",
    description: "Ami Banglay Gaan Gai - Song by Pratul Mukhopadhyay",
    url: "/graffiti_images/jibonando_kobita.jpg",
    thumbnail_url: "/graffiti_thumbnails/jibonando_kobita.jpg",
  },
  {
    id: "25",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/agun_agun.jpg",
    thumbnail_url: "/graffiti_thumbnails/agun_agun.jpg",
  },
  {
    id: "38",
    location: "Mymensingh",
    district: "Mymensingh",
    photoCredit: "Unknown",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/graffiti_street.jpg",
    thumbnail_url: "/graffiti_thumbnails/graffiti_street.jpg",
  },
  {
    id: "35",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/desh_shonkskar.jpg",
    thumbnail_url: "/graffiti_thumbnails/desh_shonkskar.jpg",
  },
  {
    id: "50",
    location: "Malibagh mor, Dhaka",
    district: "Dhaka",
    photoCredit: "Sadia Akter",
    artists: "Unknown",
    description: "",
    url: "/graffiti_images/inqilab.jpg",
    thumbnail_url: "/graffiti_thumbnails/inqilab.jpg",
  },
  {
    id: "46",
    location: "Malibagh, Dhaka",
    district: "Dhaka",
    photoCredit: "Sadia Akter",
    artists: "Unknown",
    description: "The People's Voice",
    url: "/graffiti_images/the_peoples_voice.jpg",
    thumbnail_url: "/graffiti_thumbnails/the_peoples_voice.jpg",
  },
  {
    id: "28",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/jamuna_tv.jpg",
    thumbnail_url: "/graffiti_thumbnails/jamuna_tv.jpg",
  },
  {
    id: "8",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Kabya, Nowshin, Laisa, Mahir, Oibya",
    description: "Graffiti",
    url: "/graffiti_images/gono_manush.jpg",
    thumbnail_url: "/graffiti_thumbnails/gono_manush.jpg",
  },
  {
    id: "3",
    location: "Tejgaon, Dhaka",
    district: "Dhaka",
    photoCredit: "Ashfaq Hossain Khan",
    artists: "Unknown",
    description: "Beautiful portrayal of unity ",
    url: "/graffiti_images/pata_chera_nished.jpg",
    thumbnail_url: "/graffiti_thumbnails/pata_chera_nished.jpg",
  },
  {
    id: "43",
    location: "Rajarbagh, Dhaka",
    district: "Dhaka",
    photoCredit: "Sadia Akter",
    artists: "Tanvir, Nazim, Niloy, Alvy, Happy, Jannatul",
    description: "Depicting a previous incident",
    url: "/graffiti_images/flag_on_post.jpg",
    thumbnail_url: "/graffiti_thumbnails/flag_on_post.jpg",
  },
  {
    id: "19",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/tatakae.jpg",
    thumbnail_url: "/graffiti_thumbnails/tatakae.jpg",
  },
  {
    id: "16",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/36July.jpg",
    thumbnail_url: "/graffiti_thumbnails/36July.jpg",
  },
  {
    id: "40",
    location: "Central Shahid Minar Road , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/child_copter.jpg",
    thumbnail_url: "/graffiti_thumbnails/child_copter.jpg",
  },
  {
    id: "9",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/bikkhob.jpg",
    thumbnail_url: "/graffiti_thumbnails/bikkhob.jpg",
  },
  {
    id: "11",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Efti, Shela, Tasmia",
    description: "Graffiti",
    url: "/graffiti_images/injured.jpg",
    thumbnail_url: "/graffiti_thumbnails/injured.jpg",
  },
  {
    id: "30",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/gahilam.jpg",
    thumbnail_url: "/graffiti_thumbnails/gahilam.jpg",
  },
  {
    id: "22",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/onek_manush.jpg",
    thumbnail_url: "/graffiti_thumbnails/onek_manush.jpg",
  },
  {
    id: "13",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/natok_kom_koro_pio.jpg",
    thumbnail_url: "/graffiti_thumbnails/natok_kom_koro_pio.jpg",
  },
  {
    id: "15",
    location: "Jagannath Hall, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/satellite.jpg",
    thumbnail_url: "/graffiti_thumbnails/satellite.jpg",
  },
  {
    id: "47",
    location: "Bhuigor bus stand, Underpass, Naraynganj",
    district: "Naraynganj",
    photoCredit: "Maya",
    artists: "Maya, Mithila ",
    description: "",
    url: "/graffiti_images/maya.jpg",
    thumbnail_url: "/graffiti_thumbnails/maya.jpg",
  },
  {
    id: "7",
    location: "Central Shahid Minar Road , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Rahat, Simi, Hayat, Sifat",
    description: "Graffiti",
    url: "/graffiti_images/starry_night.jpg",
    thumbnail_url: "/graffiti_thumbnails/starry_night.jpg",
  },
  {
    id: "24",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/arise.jpg",
    thumbnail_url: "/graffiti_thumbnails/arise.jpg",
  },
  {
    id: "21",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/jatrira_hushiar.jpg",
    thumbnail_url: "/graffiti_thumbnails/jatrira_hushiar.jpg",
  },
  {
    id: "32",
    location: "Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Afsana Hoque Nayan",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/shobbho_ho.jpg",
    thumbnail_url: "/graffiti_thumbnails/shobbho_ho.jpg",
  },
  {
    id: "10",
    location: "Fuller Road, Dhaka University Area , Dhaka",
    district: "Dhaka",
    photoCredit: "Sirajum Munira Shifat",
    artists: "Unknown",
    description: "Graffiti",
    url: "/graffiti_images/gujob_raw.jpg",
    thumbnail_url: "/graffiti_thumbnails/gujob_raw.jpg",
  },
];

export default graffitiImages;
